// LOGIN REQUESTS
export const CHECK_LOGIN_REQUESTED = 'CHECK_LOGIN_REQUESTED'
export const CHECK_LOGIN_SUCCEEDED = 'CHECK_LOGIN_SUCCEEDED'
export const CHECK_LOGIN_FAILED = 'CHECK_LOGIN_FAILED'
export const CHECK_LOGIN_INITIAL = 'CHECK_LOGIN_INITIAL'

// PASS REMAINDER REQUESTS
export const PASS_REMIND_REQUESTED = 'PASS_REMIND_REQUESTED'
export const PASS_REMIND_SUCCEEDED = 'PASS_REMIND_SUCCEEDED'
export const PASS_REMIND_FAILED = 'PASS_REMIND_FAILED'
export const PASS_REMIND_INITIAL = 'PASS_REMIND_INITIAL'

// REGISTER REQUESTS
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED'
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_INITIAL = 'REGISTER_INITIAL'
