// LOGIN REQUESTS
export const CHECK_LOGIN_REQUESTED = 'CHECK_LOGIN_REQUESTED'
export const CHECK_LOGIN_SUCCEEDED = 'CHECK_LOGIN_SUCCEEDED'
export const CHECK_LOGIN_FAILED = 'CHECK_LOGIN_FAILED'
export const CHECK_LOGIN_INITIAL = 'CHECK_LOGIN_INITIAL'

// GET NOTIFICATIONS
export const GET_NOTIFICATIONS_REQUESTED = 'GET_NOTIFICATIONS_REQUESTED'
export const GET_NOTIFICATIONS_SUCCEEDED = 'GET_NOTIFICATIONS_SUCCEEDED'
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED'
export const GET_NOTIFICATIONS_INITIAL = 'GET_NOTIFICATIONS_INITIAL'
