export const SET_USER_AUTH = 'SET_USER_AUTH'
export const SET_TOKEN_EXPIRED = 'SET_TOKEN_EXPIRED'
export const CLEAR_USER_AUTH_DATA = 'CLEAR_USER_AUTH_DATA'
export const SET_COLLECTION_OF_SUBSCRIPTIONS = 'SET_COLLECTION_OF_SUBSCRIPTIONS'
